package org.itson.pruebas.gestionhabitos.view;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Eliana Monge
 * @author Cristina Castro
 * @author Eduardo Talavera
 * @author Roberto García
 */
public class FrameContenedor extends javax.swing.JFrame {

    private JPanel panelActual;
    private JLabel fondoLabel;  // JLabel para la imagen de fondo
    private JLayeredPane layeredPane;  // Para manejar la superposición de paneles
    private static final Logger logger = Logger.getLogger(FrameContenedor.class.getName());

    public FrameContenedor() {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            logger.log(Level.WARNING, "Failed to initialize LaF");
        }

//        setUndecorated(true);
        initComponents();
        setBackgroundImage();  // Método para establecer la imagen de fondo
    }

    // Método para configurar la imagen de fondo
    private void setBackgroundImage() {
        // Crear el JLabel con la imagen de fondo
        fondoLabel = new JLabel(new ImageIcon(getClass().getResource("/img/fondo.png")));
        fondoLabel.setLayout(new BorderLayout());

        // Crear el JLayeredPane para manejar la superposición de la imagen de fondo y los paneles
        layeredPane = new JLayeredPane();
        layeredPane.setLayout(null);  // Permitir un layout absoluto

        // Añadir el JLabel con la imagen al fondo (capa más baja)
        fondoLabel.setBounds(0, 0, getWidth(), getHeight());  // Asegurar que cubra todo el JFrame
        layeredPane.add(fondoLabel, Integer.valueOf(0));  // Añadir en la capa más baja (0)

        // Añadir el layeredPane al JFrame
        setContentPane(layeredPane);

        // Forzar actualización de layout y repintar
        fondoLabel.revalidate();
        fondoLabel.repaint();

        // Configurar propiedades del frame
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Infloria");
        setLayout(null);  // Desactivar cualquier layout manager predeterminado
        setMinimumSize(new java.awt.Dimension(500, 550));
        setLocationRelativeTo(null);  // Centrar en la pantalla
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Infloria");
        setMinimumSize(new java.awt.Dimension(500, 550));
        setName("gestioHabitos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 550));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Método para limpiar el contenido de la ventana. Si hay un panel actualmente mostrado, lo elimina de la ventana.
     */
    public void limpiarFrame() {
        if (panelActual != null) {
            layeredPane.remove(panelActual);  // Eliminar el panel actual del layeredPane
            panelActual = null;
            layeredPane.revalidate();  // Revalidar para actualizar el layout
            layeredPane.repaint();  // Repaint para reflejar los cambios
        }
    }

    /**
     * Método para agregar un panel a la ventana. Este método agrega el panel especificado a la ventana, lo posiciona y ajusta su tamaño automáticamente.
     *
     * @param panel El panel que se va a agregar a la ventana.
     */
    public void ponerEnFrame(JPanel panel) {
        limpiarFrame();  // Limpiar cualquier panel existente

        // Asegurar que el panel nuevo sea transparente
        panel.setOpaque(false);

        // Ajustar tamaño del panel y añadirlo a una capa superior
        panel.setBounds(0, 0, 500, 550);  // Ajusta el tamaño según sea necesario
        layeredPane.add(panel, Integer.valueOf(1));  // Añadir en una capa superior (1)

        panelActual = panel;
        layeredPane.revalidate();  // Revalidar el layout
        layeredPane.repaint();  // Repaint para reflejar los cambios
    }

    // Métodos de aviso, confirmación, etc., sin cambios
    public void mostrarAviso(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.WARNING_MESSAGE);
    }

    public boolean mostrarConfirmacion(String mensaje, String titulo) {
        int respuesta = JOptionPane.showConfirmDialog(null, mensaje, titulo, JOptionPane.OK_CANCEL_OPTION);
        return respuesta == JOptionPane.OK_OPTION;
    }

    public void mostrarInformacion(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    public void mostrarInicioSesion() {
        limpiarFrame();
        InicioSesion inicioSesion = new InicioSesion(this);
        ponerEnFrame(inicioSesion);
    }

    public void mostrarInicio() {
        limpiarFrame();
        Inicio inicio = new Inicio(this);
        ponerEnFrame(inicio);
    }

    public void mostrarRegistrarUsuario() {
        limpiarFrame();
        RegistrarUsuario registrarUsuario = new RegistrarUsuario(this);
        ponerEnFrame(registrarUsuario);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
