package org.itson.pruebas.gestionhabitos.view;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.TextStyle;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import org.itson.pruebas.gestionhabitos.controller.ControllerException;
import org.itson.pruebas.gestionhabitos.controller.FechaUtil;
import org.itson.pruebas.gestionhabitos.controller.GestionarHabitosNegocio;
import org.itson.pruebas.gestionhabitos.controller.HabitoDTO;
import org.itson.pruebas.gestionhabitos.controller.HistorialHabitosDTO;
import org.itson.pruebas.gestionhabitos.controller.IGestionarHabitosNegocio;
import org.itson.pruebas.gestionhabitos.controller.Sesion;

/**
 *
 * @author Eliana Monge
 * @author Cristina Castro
 * @author Eduardo Talavera
 * @author Roberto García
 */
public class Inicio extends javax.swing.JPanel {

    private static final Logger logger = Logger.getLogger(Inicio.class.getName());
    private final FrameContenedor frame;
    private List<HistorialHabitosDTO> historialHabitos;
    private JPanel pnlHabitosPendientes;
    private JPanel pnlHabitosRealizados;
    private IGestionarHabitosNegocio gestionar;
    private LocalDate fechaActual;
    private Date[] lista;

    /**
     * Creates new form Inicio
     *
     * @param frame
     */
    public Inicio(FrameContenedor frame) {
        initComponents();
        // Inicializar variables
        lista = new Date[7];
        gestionar = new GestionarHabitosNegocio();
        fechaActual = FechaUtil.getFechaActual() == null ? LocalDate.now() : FechaUtil.getFechaActual();
        cargarDias(Date.from(fechaActual.atStartOfDay(ZoneId.systemDefault()).toInstant()));
        this.frame = frame;

        try {
            setFonts();  // Configurar fuentes
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }

        actualizarHistorialHabitos();
        setearDatos(); // Llama a mostrarHabitos y establece el nombre del usuario
    }

    public final void setearDatos() {
        try {
            mostrarHabitos();
            lblNombreUsuario.setText(Sesion.getCuenta().getNombre());
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMes = new javax.swing.JLabel();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        btnDia1 = new javax.swing.JButton();
        btnDia2 = new javax.swing.JButton();
        btnDia3 = new javax.swing.JButton();
        btnDia4 = new javax.swing.JButton();
        btnDia5 = new javax.swing.JButton();
        btnDia6 = new javax.swing.JButton();
        btnDia7 = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        pnlContenedorHabitosPendientes = new javax.swing.JPanel();
        pnlContenedorHabitosRealizados = new javax.swing.JPanel();
        lblHabitosPendientes = new javax.swing.JLabel();
        lblHabitosRealizados = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblDivision = new javax.swing.JLabel();
        btnHoy = new javax.swing.JButton();
        btnHabitos = new javax.swing.JButton();
        btnProgreso = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        lblLunes = new javax.swing.JLabel();
        lblLunes1 = new javax.swing.JLabel();
        lblMartes = new javax.swing.JLabel();
        lblMartes1 = new javax.swing.JLabel();
        lblMiercoles = new javax.swing.JLabel();
        lblMiercoles1 = new javax.swing.JLabel();
        lblJueves = new javax.swing.JLabel();
        lblJueves1 = new javax.swing.JLabel();
        lblViernes = new javax.swing.JLabel();
        lblViernes1 = new javax.swing.JLabel();
        lblSabado = new javax.swing.JLabel();
        lblSabado1 = new javax.swing.JLabel();
        lblDomingo = new javax.swing.JLabel();
        lblDomingo1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(750, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMes.setForeground(new java.awt.Color(255, 255, 255));
        lblMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMes.setText("mes");
        add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 69, 350, 30));

        btnIzquierda.setForeground(new java.awt.Color(245, 245, 245));
        btnIzquierda.setBorderPainted(false);
        btnIzquierda.setContentAreaFilled(false);
        btnIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIzquierda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });
        add(btnIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 105, 16, 27));

        btnDerecha.setForeground(new java.awt.Color(245, 245, 245));
        btnDerecha.setBorderPainted(false);
        btnDerecha.setContentAreaFilled(false);
        btnDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDerecha.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });
        add(btnDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 105, 16, 27));

        btnDia1.setForeground(new java.awt.Color(245, 245, 245));
        btnDia1.setBorderPainted(false);
        btnDia1.setContentAreaFilled(false);
        btnDia1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia1ActionPerformed(evt);
            }
        });
        add(btnDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 106, 60, 60));

        btnDia2.setForeground(new java.awt.Color(245, 245, 245));
        btnDia2.setBorderPainted(false);
        btnDia2.setContentAreaFilled(false);
        btnDia2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia2ActionPerformed(evt);
            }
        });
        add(btnDia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 106, 60, 60));

        btnDia3.setForeground(new java.awt.Color(245, 245, 245));
        btnDia3.setBorderPainted(false);
        btnDia3.setContentAreaFilled(false);
        btnDia3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia3ActionPerformed(evt);
            }
        });
        add(btnDia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 106, 60, 60));

        btnDia4.setForeground(new java.awt.Color(245, 245, 245));
        btnDia4.setBorderPainted(false);
        btnDia4.setContentAreaFilled(false);
        btnDia4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia4ActionPerformed(evt);
            }
        });
        add(btnDia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 106, 60, 60));

        btnDia5.setForeground(new java.awt.Color(245, 245, 245));
        btnDia5.setBorderPainted(false);
        btnDia5.setContentAreaFilled(false);
        btnDia5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia5ActionPerformed(evt);
            }
        });
        add(btnDia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 106, 60, 60));

        btnDia6.setForeground(new java.awt.Color(245, 245, 245));
        btnDia6.setBorderPainted(false);
        btnDia6.setContentAreaFilled(false);
        btnDia6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia6ActionPerformed(evt);
            }
        });
        add(btnDia6, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 106, 60, 60));

        btnDia7.setForeground(new java.awt.Color(245, 245, 245));
        btnDia7.setBorderPainted(false);
        btnDia7.setContentAreaFilled(false);
        btnDia7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia7ActionPerformed(evt);
            }
        });
        add(btnDia7, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 106, 60, 60));

        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 9, 46, 46));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarHabitos.png"))); // NOI18N
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 572, 50, -1));

        pnlContenedorHabitosPendientes.setOpaque(false);
        add(pnlContenedorHabitosPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 233, 700, 170));

        pnlContenedorHabitosRealizados.setOpaque(false);
        add(pnlContenedorHabitosRealizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 460, 700, 170));

        lblHabitosPendientes.setText("HÁBITOS PENDIENTES");
        add(lblHabitosPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 198, -1, -1));

        lblHabitosRealizados.setText("HÁBITOS REALIZADOS");
        add(lblHabitosRealizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 425, -1, -1));

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("fecha");
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 193, 410, 25));

        lblDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/division.png"))); // NOI18N
        add(lblDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 415, -1, -1));

        btnHoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hoy.png"))); // NOI18N
        btnHoy.setBorderPainted(false);
        btnHoy.setContentAreaFilled(false);
        btnHoy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoyActionPerformed(evt);
            }
        });
        add(btnHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 654, 80, 81));

        btnHabitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/habitos.png"))); // NOI18N
        btnHabitos.setBorderPainted(false);
        btnHabitos.setContentAreaFilled(false);
        btnHabitos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHabitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitosActionPerformed(evt);
            }
        });
        add(btnHabitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 654, 80, 81));

        btnProgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/progreso.png"))); // NOI18N
        btnProgreso.setBorderPainted(false);
        btnProgreso.setContentAreaFilled(false);
        btnProgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgresoActionPerformed(evt);
            }
        });
        add(btnProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 654, 80, 81));

        lblNombreUsuario.setForeground(new java.awt.Color(37, 52, 18));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 18, 300, 27));

        lblLunes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLunes.setForeground(new java.awt.Color(255, 255, 255));
        lblLunes.setText("L");
        add(lblLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 10, 20));

        lblLunes1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLunes1.setForeground(new java.awt.Color(255, 255, 255));
        lblLunes1.setText("21");
        add(lblLunes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 130, 30, 20));

        lblMartes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMartes.setForeground(new java.awt.Color(255, 255, 255));
        lblMartes.setText("M");
        add(lblMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 30, 20));

        lblMartes1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMartes1.setForeground(new java.awt.Color(255, 255, 255));
        lblMartes1.setText("22");
        add(lblMartes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 130, 60, 20));

        lblMiercoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMiercoles.setForeground(new java.awt.Color(255, 255, 255));
        lblMiercoles.setText("X");
        add(lblMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 10, 20));

        lblMiercoles1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMiercoles1.setForeground(new java.awt.Color(255, 255, 255));
        lblMiercoles1.setText("23");
        add(lblMiercoles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 130, 60, 20));

        lblJueves.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJueves.setForeground(new java.awt.Color(255, 255, 255));
        lblJueves.setText("J");
        add(lblJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 10, 20));

        lblJueves1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblJueves1.setForeground(new java.awt.Color(255, 255, 255));
        lblJueves1.setText("24");
        add(lblJueves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 130, 60, 20));

        lblViernes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViernes.setForeground(new java.awt.Color(255, 255, 255));
        lblViernes.setText("V");
        add(lblViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 10, 20));

        lblViernes1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblViernes1.setForeground(new java.awt.Color(255, 255, 255));
        lblViernes1.setText("25");
        add(lblViernes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 130, 50, 20));

        lblSabado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSabado.setForeground(new java.awt.Color(255, 255, 255));
        lblSabado.setText("S");
        add(lblSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 10, 20));

        lblSabado1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSabado1.setForeground(new java.awt.Color(255, 255, 255));
        lblSabado1.setText("26");
        add(lblSabado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 130, 60, 20));

        lblDomingo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDomingo.setForeground(new java.awt.Color(255, 255, 255));
        lblDomingo.setText("D");
        add(lblDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 10, 20));

        lblDomingo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDomingo1.setForeground(new java.awt.Color(255, 255, 255));
        lblDomingo1.setText("27");
        add(lblDomingo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 130, 60, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHoyActionPerformed

    private void btnProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgresoActionPerformed
        frame.mostrarProgresoSemanal();
    }//GEN-LAST:event_btnProgresoActionPerformed

    private void btnHabitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitosActionPerformed
        frame.mostrarListaHabitos();
    }//GEN-LAST:event_btnHabitosActionPerformed

    private void btnDia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia1ActionPerformed
        // TODO add your handling code here:

        fechaActual = lista[0].toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        String nombreDia = fechaActual.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("es"));
        String mes = fechaActual.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

        FechaUtil.setFechaFormateada(nombreDia + " " + fechaActual.getDayOfMonth() + " de " + mes + " de " + fechaActual.getYear());
        try {
            historialHabitos = gestionar.obtenerHabitosDia(fechaActual, "lunes");
            HistorialHabitosDTO.setHistorialHabitosDTOs(historialHabitos);
        } catch (ControllerException ex) {
            logger.log(Level.WARNING, ex.getMessage());
        } catch (NoSuchElementException e) {
            logger.log(Level.INFO, "El usuario no tiene hábitos asignados este día");
            HistorialHabitosDTO.setHistorialHabitosDTOs(new ArrayList<>());

        }
        FechaUtil.setFechaActual(fechaActual);
        frame.mostrarInicio();
    }//GEN-LAST:event_btnDia1ActionPerformed

    private void btnDia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia2ActionPerformed
        // TODO add your handling code here:
        fechaActual = lista[1].toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        String nombreDia = fechaActual.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("es"));
        String mes = fechaActual.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

        FechaUtil.setFechaFormateada(nombreDia + " " + fechaActual.getDayOfMonth() + " de " + mes + " de " + fechaActual.getYear());
        try {
            historialHabitos = gestionar.obtenerHabitosDia(fechaActual, "martes");
            HistorialHabitosDTO.setHistorialHabitosDTOs(historialHabitos);
        } catch (ControllerException ex) {
            logger.log(Level.WARNING, ex.getMessage());
        } catch (NoSuchElementException e) {
            logger.log(Level.INFO, "El usuario no tiene hábitos asignados este día");
            HistorialHabitosDTO.setHistorialHabitosDTOs(new ArrayList<>());
        }
        FechaUtil.setFechaActual(fechaActual);

        frame.mostrarInicio();
    }//GEN-LAST:event_btnDia2ActionPerformed

    private void btnDia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia3ActionPerformed
        // TODO add your handling code here:
        fechaActual = lista[2].toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        String nombreDia = fechaActual.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("es"));
        String mes = fechaActual.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

        FechaUtil.setFechaFormateada(nombreDia + " " + fechaActual.getDayOfMonth() + " de " + mes + " de " + fechaActual.getYear());
        try {
            historialHabitos = gestionar.obtenerHabitosDia(fechaActual, "miercoles");
            HistorialHabitosDTO.setHistorialHabitosDTOs(historialHabitos);
        } catch (ControllerException ex) {
            logger.log(Level.WARNING, ex.getMessage());
        } catch (NoSuchElementException e) {
            logger.log(Level.INFO, "El usuario no tiene hábitos asignados este día");
            HistorialHabitosDTO.setHistorialHabitosDTOs(new ArrayList<>());
        }
        frame.mostrarInicio();
    }//GEN-LAST:event_btnDia3ActionPerformed

    private void btnDia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia4ActionPerformed
        // TODO add your handling code here:
        fechaActual = lista[3].toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        String nombreDia = fechaActual.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("es"));
        String mes = fechaActual.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

        FechaUtil.setFechaFormateada(nombreDia + " " + fechaActual.getDayOfMonth() + " de " + mes + " de " + fechaActual.getYear());
        try {
            historialHabitos = gestionar.obtenerHabitosDia(fechaActual, "jueves");
            HistorialHabitosDTO.setHistorialHabitosDTOs(historialHabitos);
        } catch (ControllerException ex) {
            logger.log(Level.WARNING, ex.getMessage());
        } catch (NoSuchElementException e) {
            logger.log(Level.INFO, "El usuario no tiene hábitos asignados este día");
            HistorialHabitosDTO.setHistorialHabitosDTOs(new ArrayList<>());
        }
        frame.mostrarInicio();
    }//GEN-LAST:event_btnDia4ActionPerformed

    private void btnDia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia5ActionPerformed
        // TODO add your handling code here:
        fechaActual = lista[4].toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        String nombreDia = fechaActual.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("es"));
        String mes = fechaActual.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

        FechaUtil.setFechaFormateada(nombreDia + " " + fechaActual.getDayOfMonth() + " de " + mes + " de " + fechaActual.getYear());
        try {
            historialHabitos = gestionar.obtenerHabitosDia(fechaActual, "viernes");
            HistorialHabitosDTO.setHistorialHabitosDTOs(historialHabitos);
        } catch (ControllerException ex) {
            logger.log(Level.WARNING, ex.getMessage());
        } catch (NoSuchElementException e) {
            logger.log(Level.INFO, "El usuario no tiene hábitos asignados este día");
            HistorialHabitosDTO.setHistorialHabitosDTOs(new ArrayList<>());
        }
        frame.mostrarInicio();
    }//GEN-LAST:event_btnDia5ActionPerformed

    private void btnDia6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia6ActionPerformed
        // TODO add your handling code here:
        fechaActual = lista[5].toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        String nombreDia = fechaActual.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("es"));
        String mes = fechaActual.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

        FechaUtil.setFechaFormateada(nombreDia + " " + fechaActual.getDayOfMonth() + " de " + mes + " de " + fechaActual.getYear());
        try {
            historialHabitos = gestionar.obtenerHabitosDia(fechaActual, "sabado");
            HistorialHabitosDTO.setHistorialHabitosDTOs(historialHabitos);
        } catch (ControllerException ex) {
            logger.log(Level.WARNING, ex.getMessage());
        } catch (NoSuchElementException e) {
            logger.log(Level.INFO, "El usuario no tiene hábitos asignados este día");
            HistorialHabitosDTO.setHistorialHabitosDTOs(new ArrayList<>());
        }
        frame.mostrarInicio();
    }//GEN-LAST:event_btnDia6ActionPerformed

    private void btnDia7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia7ActionPerformed
        // TODO add your handling code here:
        fechaActual = lista[6].toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        String nombreDia = fechaActual.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("es"));
        String mes = fechaActual.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

        FechaUtil.setFechaFormateada(nombreDia + " " + fechaActual.getDayOfMonth() + " de " + mes + " de " + fechaActual.getYear());
        try {
            historialHabitos = gestionar.obtenerHabitosDia(fechaActual, "domingo");
            HistorialHabitosDTO.setHistorialHabitosDTOs(historialHabitos);
        } catch (ControllerException ex) {
            logger.log(Level.WARNING, ex.getMessage());
        } catch (NoSuchElementException e) {
            logger.log(Level.INFO, "El usuario no tiene hábitos asignados este día");
            HistorialHabitosDTO.setHistorialHabitosDTOs(new ArrayList<>());
        }
        frame.mostrarInicio();
    }//GEN-LAST:event_btnDia7ActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        try {
            Date fecha = Date.from(fechaActual.atStartOfDay(ZoneId.systemDefault()).toInstant());
            lista = gestionar.obtenerSemana(gestionar.obtenerSemana(fecha), "anterior");

            // Formatear los días y establecer el texto en las etiquetas
            lblLunes1.setText(String.format("%02d", lista[0].getDate()));
            lblMartes1.setText(String.format("%02d", lista[1].getDate()));
            lblMiercoles1.setText(String.format("%02d", lista[2].getDate()));
            lblJueves1.setText(String.format("%02d", lista[3].getDate()));
            lblViernes1.setText(String.format("%02d", lista[4].getDate()));
            lblSabado1.setText(String.format("%02d", lista[5].getDate()));
            lblDomingo1.setText(String.format("%02d", lista[6].getDate()));

            // Obtener LocalDate para el primer y último día de la semana
            LocalDate primerDia = lista[0].toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();
            LocalDate ultimoDia = lista[6].toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();

            // Obtener los meses y años correspondientes
            String mesInicio = primerDia.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();
            String mesFin = ultimoDia.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

            int anioInicio = primerDia.getYear();
            int anioFin = ultimoDia.getYear();

            // Determinar la salida de la etiqueta lblMes
            if (!mesInicio.equals(mesFin)) {
                // Si los meses son diferentes
                if (anioInicio == anioFin) {
                    // Si los años son iguales, formatear como "mes1 - mes2 año"
                    lblMes.setText(mesInicio + " - " + mesFin + " " + anioInicio);
                } else {
                    // Si los años son diferentes, formatear como "mes1 año1 - mes2 año2"
                    lblMes.setText(mesInicio + " " + anioInicio + " - " + mesFin + " " + anioFin);
                }
            } else {
                // Si los meses son iguales
                lblMes.setText(mesInicio + " " + anioInicio);
            }

            fechaActual = primerDia;
        } catch (ControllerException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        // TODO add your handling code here:
        try {
            Date fecha = Date.from(fechaActual.atStartOfDay(ZoneId.systemDefault()).toInstant());
            lista = gestionar.obtenerSemana(gestionar.obtenerSemana(fecha), "posterior");

            // Formatear los días y establecer el texto en las etiquetas
            lblLunes1.setText(String.format("%02d", lista[0].getDate()));
            lblMartes1.setText(String.format("%02d", lista[1].getDate()));
            lblMiercoles1.setText(String.format("%02d", lista[2].getDate()));
            lblJueves1.setText(String.format("%02d", lista[3].getDate()));
            lblViernes1.setText(String.format("%02d", lista[4].getDate()));
            lblSabado1.setText(String.format("%02d", lista[5].getDate()));
            lblDomingo1.setText(String.format("%02d", lista[6].getDate()));

            // Obtener LocalDate para el primer y último día de la semana
            LocalDate primerDia = lista[0].toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();
            LocalDate ultimoDia = lista[6].toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();

            // Obtener los meses y años correspondientes
            String mesInicio = primerDia.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();
            String mesFin = ultimoDia.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

            int anioInicio = primerDia.getYear();
            int anioFin = ultimoDia.getYear();

            // Determinar la salida de la etiqueta lblMes
            if (!mesInicio.equals(mesFin)) {
                // Si los meses son diferentes
                if (anioInicio == anioFin) {
                    // Si los años son iguales, formatear como "mes1 - mes2 año"
                    lblMes.setText(mesInicio + " - " + mesFin + " " + anioInicio);
                } else {
                    // Si los años son diferentes, formatear como "mes1 año1 - mes2 año2"
                    lblMes.setText(mesInicio + " " + anioInicio + " - " + mesFin + " " + anioFin);
                }
            } else {
                // Si los meses son iguales
                lblMes.setText(mesInicio + " " + anioInicio);
            }

            fechaActual = primerDia;
        } catch (ControllerException ex) {
//            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        frame.agregarHabito(this);

        try {
            mostrarHabitos(); // Refresca la lista de hábitos
        } catch (FontFormatException | IOException e) {
//            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        frame.mostrarOpcionesPerfil();
    }//GEN-LAST:event_btnPerfilActionPerformed

//    public List<HistorialHabitosDTO> obtenerHabitosDia(LocalDate dia, String diaString) throws ControllerException {
//        List<HabitoDTO> habitos = gestionar.identificarDias(Sesion.getCuenta(), diaString);
//        Date diaDate = Date.from(dia.atStartOfDay(ZoneId.systemDefault()).toInstant());
//        for (HabitoDTO habito : habitos) {
//            try {
//                HistorialHabitosDTO historialHabitosDTO = gestionar.buscarPorFechaYIdHabito(diaDate, habito.getId());
//                historialHabitos.add(historialHabitosDTO);
//            } catch (ControllerException e) {
//                historialHabitos.add(gestionar.guardarHistorial(new HistorialHabitosDTO(diaDate, false, habito)));
//            }
//
//        }
//        return historialHabitos;
//    }
    private void actualizarHistorialHabitos() {
        try {
            historialHabitos = obtenerHistorial(new Date());
        } catch (ControllerException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void mostrarHabitos() throws FontFormatException, IOException {
        historialHabitos = HistorialHabitosDTO.getHistorialHabitosDTOs();
        listarHabitosPendientes();
        listarHabitosRealizados();

        if (pnlHabitosPendientes != null) {
            pnlHabitosPendientes.revalidate();
            pnlHabitosPendientes.repaint();
        }
        if (pnlHabitosRealizados != null) {
            pnlHabitosRealizados.revalidate();
            pnlHabitosRealizados.repaint();
        }
    }

    private void listarHabitosPendientes() throws FontFormatException, IOException {
        if (pnlHabitosPendientes == null) {
            pnlHabitosPendientes = new JPanel();
            pnlHabitosPendientes.setLayout(new BoxLayout(pnlHabitosPendientes, BoxLayout.Y_AXIS));
            pnlHabitosPendientes.setName("pnlHabitosPendientes");
            pnlHabitosPendientes.setOpaque(false);

            JScrollPane scpHabitosPendientes = new JScrollPane(pnlHabitosPendientes);
            scpHabitosPendientes.setOpaque(false);
            scpHabitosPendientes.getViewport().setOpaque(false);
            scpHabitosPendientes.setBorder(null);
            scpHabitosPendientes.getVerticalScrollBar().setUnitIncrement(16);
            scpHabitosPendientes.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            scpHabitosPendientes.setPreferredSize(new Dimension(700, 170));

            pnlContenedorHabitosPendientes.add(scpHabitosPendientes);
        } else {
            pnlHabitosPendientes.removeAll();
        }

        try {
            GestionarHabitosNegocio gestion = new GestionarHabitosNegocio();

            if (!historialHabitos.isEmpty()) {
                for (HistorialHabitosDTO habito : historialHabitos) {
                    if (!gestion.habitoCompletado(habito.getHabito())) {
                        System.out.println(habito.getHabito().getNombre());
                        addHabit(habito, false);
                    }
                }
            } else {
                JLabel noHabitsLabel = new JLabel("No hay hábitos pendientes el día de hoy.");
                noHabitsLabel.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-Regular.ttf", 18F));
                pnlHabitosPendientes.add(noHabitsLabel);
            }
        } catch (ControllerException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, "Error al listar hábitos pendientes", ex);
        }

        pnlHabitosPendientes.revalidate();
        pnlHabitosPendientes.repaint();
    }

    private void registrarHabito(HabitoDTO habitoDTO, Boolean isDone) throws FontFormatException, IOException {
        try {
            new GestionarHabitosNegocio().guardarHistorial(
                    new HistorialHabitosDTO(
                            FechaUtil.convertirLocalDateADate(FechaUtil.getFechaActual()), 
                            isDone, 
                            habitoDTO));

        } catch (ControllerException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void listarHabitosRealizados() throws FontFormatException, IOException {
        if (pnlHabitosRealizados == null) {
            pnlHabitosRealizados = new JPanel();
            pnlHabitosRealizados.setLayout(new BoxLayout(pnlHabitosRealizados, BoxLayout.Y_AXIS));
            pnlHabitosRealizados.setName("pnlHabitosRealizados");
            pnlHabitosRealizados.setOpaque(false);

            JScrollPane scpHabitosRealizados = new JScrollPane(pnlHabitosRealizados);
            scpHabitosRealizados.setOpaque(false);
            scpHabitosRealizados.getViewport().setOpaque(false);
            scpHabitosRealizados.setBorder(null);
            scpHabitosRealizados.getVerticalScrollBar().setUnitIncrement(16);
            scpHabitosRealizados.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            scpHabitosRealizados.setPreferredSize(new Dimension(700, 170));

            pnlContenedorHabitosRealizados.add(scpHabitosRealizados);
        } else {
            pnlHabitosRealizados.removeAll();
        }

        GestionarHabitosNegocio gestion = new GestionarHabitosNegocio();

        if (!historialHabitos.isEmpty()) {
            for (HistorialHabitosDTO habito : historialHabitos) {
                try {
                    if (gestion.habitoCompletado(habito.getHabito())) {
                        System.out.println(habito.getHabito().getNombre());
                        addHabit(habito, true);
                    }
                } catch (ControllerException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JLabel noHabitsLabel = new JLabel("No hay hábitos realizados el día de hoy.");
            noHabitsLabel.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-Regular.ttf", 18F));

            pnlHabitosRealizados.add(noHabitsLabel);
        }

        pnlHabitosRealizados.revalidate();
        pnlHabitosRealizados.repaint();
    }

    private void addHabit(HistorialHabitosDTO habitoDTO, boolean isCompleted) throws FontFormatException, IOException {
        String habitName = habitoDTO.getHabito().getNombre();
        HabitPanel habit = new HabitPanel(habitName, isCompleted);

        habit.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    if (!habit.isCompleted()) {
                        pnlHabitosPendientes.remove(habit);
                        if (pnlHabitosRealizados == null) {
                            pnlHabitosRealizados = new JPanel();
                        }
                        System.out.println("agrega un habito a habitos realizados");
                        pnlHabitosRealizados.add(habit);
                        habit.setCompleted(true);
                        System.out.println("aqui si entra, esta es si se pasa de pendiente a realizado");
                        registrarHabito(habitoDTO.getHabito(), true);
                        actualizarHistorialHabitos();
                    } else {
                        pnlHabitosRealizados.remove(habit);
                        System.out.println("agrega un habito a habitos pendientes");
                        pnlHabitosPendientes.add(habit);
                        habit.setCompleted(false);
                        System.out.println("es de realizado a pendiente");
                        registrarHabito(habitoDTO.getHabito(), false);
                        actualizarHistorialHabitos();
                    }

                    pnlHabitosPendientes.revalidate();
                    pnlHabitosPendientes.repaint();

                    if (pnlHabitosRealizados != null) {
                        pnlHabitosRealizados.revalidate();
                        pnlHabitosRealizados.repaint();
                    }

                    if (pnlHabitosPendientes != null) {
                        pnlHabitosPendientes.revalidate();
                        pnlHabitosPendientes.repaint();
                    }

                } catch (FontFormatException | IOException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        if (isCompleted) {
            if (pnlHabitosRealizados == null) {
                pnlHabitosRealizados = new JPanel();
            }
            pnlHabitosRealizados.add(habit);
        } else {
            pnlHabitosPendientes.add(habit);
        }

        // Update the UI
        pnlHabitosPendientes.revalidate();
        pnlHabitosPendientes.repaint();
        if (pnlHabitosRealizados != null) {
            pnlHabitosRealizados.revalidate();
            pnlHabitosRealizados.repaint();
        }
    }

// Panel personalizado para cada hábito
    private class HabitPanel extends JPanel {

        private Boolean isCompleted;
        private final JLabel imagePanel;

        public HabitPanel(String habitName, Boolean isCompleted) throws FontFormatException, IOException {
            this.isCompleted = isCompleted;

            setLayout(new FlowLayout(FlowLayout.LEFT));
            setPreferredSize(new Dimension(0, 30));  // Altura fija de 30, ancho ajustable
            setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));  // Establece la altura máxima

            JLabel nameLabel = new JLabel(habitName);
            nameLabel.setHorizontalAlignment(SwingConstants.LEFT);
            nameLabel.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-Regular.ttf", 18F));

            // Imagen opcional (ejemplo con un cuadrado de color)
            imagePanel = new JLabel(new ImageIcon(getClass().getResource(isCompleted
                    ? "/img/checkColoreado.png"
                    : "/img/checkVacio.png")));

            setCursor(new Cursor(java.awt.Cursor.HAND_CURSOR));
            setOpaque(false);
            setBorder(BorderFactory.createEmptyBorder(0, 0, 20, 0));  // Espacio de 8px en la parte inferior

            add(imagePanel);
            add(nameLabel);
        }

        public Boolean isCompleted() {
            return isCompleted;
        }

        public void setCompleted(Boolean completed) {
            this.isCompleted = completed;
            // Cambiar el ícono de la imagen dependiendo del estado
            imagePanel.setIcon(new ImageIcon(getClass().getResource(completed
                    ? "/img/checkColoreado.png"
                    : "/img/checkVacio.png")));
        }
    }

    private List<HistorialHabitosDTO> obtenerHistorial(Date fecha) throws ControllerException {
        return gestionar.consultarHistorialHabitos(fecha, Sesion.getCuenta());
    }

    private void setFonts() throws FontFormatException, IOException {
        lblNombreUsuario.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-Medium.ttf", 20F));
        lblMes.setFont(frame.cargarFuente("/fonts/Kurale/Kurale-Regular.ttf", 20F));
        Font semiBoldFont = frame.cargarFuente("/fonts/Nunito/static/Nunito-SemiBold.ttf", 22F);
        Font nunitoRegular = frame.cargarFuente("/fonts/Nunito/static/Nunito-Regular.ttf", 18F);
        lblHabitosPendientes.setFont(semiBoldFont);
        lblHabitosRealizados.setFont(semiBoldFont);
        lblFecha.setFont(nunitoRegular);
        btnDia1.setFont(nunitoRegular);
        btnDia2.setFont(nunitoRegular);
        btnDia3.setFont(nunitoRegular);
        btnDia4.setFont(nunitoRegular);
        btnDia5.setFont(nunitoRegular);
        btnDia6.setFont(nunitoRegular);
        btnDia7.setFont(nunitoRegular);

    }

    private void cargarDias(Date hoy) {

        lista = gestionar.obtenerSemana(hoy);

        LocalDate primerDia = lista[0].toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        LocalDate ultimoDia = lista[6].toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        String mesInicio = primerDia.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();
        String mesFin = ultimoDia.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES")).toLowerCase();

        int anioInicio = primerDia.getYear();
        int anioFin = ultimoDia.getYear();

        if (!mesInicio.equals(mesFin)) {
            if (anioInicio == anioFin) {
                lblMes.setText(mesInicio + " - " + mesFin + " " + anioInicio);
            } else {
                lblMes.setText(mesInicio + " - " + mesFin + " " + anioFin);
            }
        } else {
            lblMes.setText(mesInicio + " " + anioInicio);
        }

        fechaActual = primerDia;

        lblLunes1.setText(String.format("%02d", lista[0].getDate()));
        lblMartes1.setText(String.format("%02d", lista[1].getDate()));
        lblMiercoles1.setText(String.format("%02d", lista[2].getDate()));
        lblJueves1.setText(String.format("%02d", lista[3].getDate()));
        lblViernes1.setText(String.format("%02d", lista[4].getDate()));
        lblSabado1.setText(String.format("%02d", lista[5].getDate()));
        lblDomingo1.setText(String.format("%02d", lista[6].getDate()));

        lblFecha.setText(FechaUtil.getFechaFormateada());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnDia1;
    private javax.swing.JButton btnDia2;
    private javax.swing.JButton btnDia3;
    private javax.swing.JButton btnDia4;
    private javax.swing.JButton btnDia5;
    private javax.swing.JButton btnDia6;
    private javax.swing.JButton btnDia7;
    private javax.swing.JButton btnHabitos;
    private javax.swing.JButton btnHoy;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnProgreso;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblDomingo;
    private javax.swing.JLabel lblDomingo1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHabitosPendientes;
    private javax.swing.JLabel lblHabitosRealizados;
    private javax.swing.JLabel lblJueves;
    private javax.swing.JLabel lblJueves1;
    private javax.swing.JLabel lblLunes;
    private javax.swing.JLabel lblLunes1;
    private javax.swing.JLabel lblMartes;
    private javax.swing.JLabel lblMartes1;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMiercoles;
    private javax.swing.JLabel lblMiercoles1;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblSabado;
    private javax.swing.JLabel lblSabado1;
    private javax.swing.JLabel lblViernes;
    private javax.swing.JLabel lblViernes1;
    private javax.swing.JPanel pnlContenedorHabitosPendientes;
    private javax.swing.JPanel pnlContenedorHabitosRealizados;
    // End of variables declaration//GEN-END:variables
}
