/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.pruebas.gestionhabitos.view;

import com.mycompany.subsistemacontroller.Sesion;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import javax.swing.JDialog;

/**
 *
 * @author user
 */
public class OpcionesUsuario extends javax.swing.JPanel {

    private final FrameContenedor frame;
    private final JDialog parentDialog;

    /**
     * Creates new form VerHabito
     *
     * @param frame
     */
    public OpcionesUsuario(FrameContenedor frame, JDialog parentDialog) {
        this.parentDialog = parentDialog;
        this.frame = frame;
        initComponents();
        setFonts();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();

        setBackground(new java.awt.Color(118, 152, 82));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setForeground(new java.awt.Color(245, 245, 245));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Sesion.cerrarSesion();
        parentDialog.dispose();
        frame.mostrarInicioSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void setFonts() {
        try {
            btnCerrarSesion.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-Bold.ttf", 18F));
        } catch (FontFormatException | IOException ex) {
            frame.mostrarAviso(ex.getMessage(), "Aviso");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    // End of variables declaration//GEN-END:variables
}
