/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.pruebas.gestionhabitos.view;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import org.itson.pruebas.gestionhabitos.controller.Sesion;

/**
 *
 * @author user
 */
public class OpcionesUsuario extends javax.swing.JPanel {

    private final FrameContenedor frame;

    /**
     * Creates new form VerHabito
     *
     * @param frame
     */
    public OpcionesUsuario(FrameContenedor frame) {
        this.frame = frame;
        initComponents();
        setFonts();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCerrarSesion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrarSesion.setText("Cerrar Sesión");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });
        add(lblCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 32, 120, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        Sesion.cerrarSesion();
        frame.mostrarInicioSesion();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void setFonts() {
        try {
            lblCerrarSesion.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-Bold.ttf", 14F));
        } catch (FontFormatException | IOException ex) {
            frame.mostrarAviso(ex.getMessage(), "Aviso");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCerrarSesion;
    // End of variables declaration//GEN-END:variables
}
