/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.pruebas.gestionhabitos.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import org.itson.pruebas.gestionhabitos.controller.ControllerException;
import org.itson.pruebas.gestionhabitos.controller.GestionarHabitosNegocio;
import org.itson.pruebas.gestionhabitos.controller.IGestionarHabitosNegocio;
import org.itson.pruebas.gestionhabitos.controller.ProgresoHabitoDTO;
import org.itson.pruebas.gestionhabitos.controller.Sesion;

/**
 *
 * @author rover
 */
public class ProgresoMensual extends javax.swing.JPanel {

    private FrameContenedor frame;
    private IGestionarHabitosNegocio gestionar;

    /**
     * Creates new form ListaHabitos
     */
    public ProgresoMensual(FrameContenedor frame) {
        this.frame = frame;

        initComponents();
        gestionar = new GestionarHabitosNegocio();
        try {
            listarHabitos();
            setFonts();
        } catch (FontFormatException | IOException | ControllerException ex) {
            frame.mostrarAviso(ex.getMessage(), "Aviso");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMes = new javax.swing.JLabel();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        btnDia1 = new javax.swing.JButton();
        btnDia2 = new javax.swing.JButton();
        btnDia3 = new javax.swing.JButton();
        btnDia4 = new javax.swing.JButton();
        btnDia5 = new javax.swing.JButton();
        btnDia6 = new javax.swing.JButton();
        btnDia7 = new javax.swing.JButton();
        btnMensual = new javax.swing.JButton();
        lblMensual = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblProgresoHabitos = new javax.swing.JLabel();
        pnlContenedorHabitos = new javax.swing.JPanel();
        btnHoy = new javax.swing.JButton();
        btnHabitos = new javax.swing.JButton();
        btnProgreso = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(750, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMes.setForeground(new java.awt.Color(255, 255, 255));
        lblMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMes.setText("mes");
        add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 69, 350, 30));

        btnIzquierda.setForeground(new java.awt.Color(245, 245, 245));
        btnIzquierda.setBorderPainted(false);
        btnIzquierda.setContentAreaFilled(false);
        btnIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIzquierda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });
        add(btnIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 105, 16, 27));

        btnDerecha.setForeground(new java.awt.Color(245, 245, 245));
        btnDerecha.setBorderPainted(false);
        btnDerecha.setContentAreaFilled(false);
        btnDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDerecha.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });
        add(btnDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 105, 16, 27));

        btnDia1.setForeground(new java.awt.Color(245, 245, 245));
        btnDia1.setText("<html>D<br>N</html>");
        btnDia1.setBorderPainted(false);
        btnDia1.setContentAreaFilled(false);
        btnDia1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia1ActionPerformed(evt);
            }
        });
        add(btnDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 106, 60, 60));

        btnDia2.setForeground(new java.awt.Color(245, 245, 245));
        btnDia2.setText("<html>D<br>N</html>");
        btnDia2.setBorderPainted(false);
        btnDia2.setContentAreaFilled(false);
        btnDia2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia2ActionPerformed(evt);
            }
        });
        add(btnDia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 106, 60, 60));

        btnDia3.setForeground(new java.awt.Color(245, 245, 245));
        btnDia3.setText("<html>D<br>N</html>");
        btnDia3.setBorderPainted(false);
        btnDia3.setContentAreaFilled(false);
        btnDia3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia3ActionPerformed(evt);
            }
        });
        add(btnDia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 106, 60, 60));

        btnDia4.setForeground(new java.awt.Color(245, 245, 245));
        btnDia4.setText("<html>D<br>N</html>");
        btnDia4.setBorderPainted(false);
        btnDia4.setContentAreaFilled(false);
        btnDia4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia4ActionPerformed(evt);
            }
        });
        add(btnDia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 106, 60, 60));

        btnDia5.setForeground(new java.awt.Color(245, 245, 245));
        btnDia5.setText("<html>D<br>N</html>");
        btnDia5.setBorderPainted(false);
        btnDia5.setContentAreaFilled(false);
        btnDia5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia5ActionPerformed(evt);
            }
        });
        add(btnDia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 106, 60, 60));

        btnDia6.setForeground(new java.awt.Color(245, 245, 245));
        btnDia6.setText("<html>D<br>N</html>");
        btnDia6.setBorderPainted(false);
        btnDia6.setContentAreaFilled(false);
        btnDia6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia6ActionPerformed(evt);
            }
        });
        add(btnDia6, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 106, 60, 60));

        btnDia7.setForeground(new java.awt.Color(245, 245, 245));
        btnDia7.setText("<html>D<br>N</html>");
        btnDia7.setBorderPainted(false);
        btnDia7.setContentAreaFilled(false);
        btnDia7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDia7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDia7ActionPerformed(evt);
            }
        });
        add(btnDia7, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 106, 60, 60));

        btnMensual.setBorderPainted(false);
        btnMensual.setContentAreaFilled(false);
        btnMensual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensualActionPerformed(evt);
            }
        });
        add(btnMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 198, 110, 43));

        lblMensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mensual.png"))); // NOI18N
        add(lblMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 198, -1, -1));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarHabitos.png"))); // NOI18N
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 579, 50, 50));

        lblProgresoHabitos.setForeground(new java.awt.Color(0, 0, 0));
        lblProgresoHabitos.setText("PROGESO DE HÁBITOS");
        add(lblProgresoHabitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 198, -1, -1));

        pnlContenedorHabitos.setOpaque(false);
        add(pnlContenedorHabitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 238, 700, 390));

        btnHoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hoy.png"))); // NOI18N
        btnHoy.setBorderPainted(false);
        btnHoy.setContentAreaFilled(false);
        btnHoy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoyActionPerformed(evt);
            }
        });
        add(btnHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 654, 80, 81));

        btnHabitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/habitos.png"))); // NOI18N
        btnHabitos.setBorderPainted(false);
        btnHabitos.setContentAreaFilled(false);
        btnHabitos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHabitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitosActionPerformed(evt);
            }
        });
        add(btnHabitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 654, 80, 81));

        btnProgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/progreso.png"))); // NOI18N
        btnProgreso.setBorderPainted(false);
        btnProgreso.setContentAreaFilled(false);
        btnProgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgresoActionPerformed(evt);
            }
        });
        add(btnProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 654, 80, 81));

        lblNombreUsuario.setForeground(new java.awt.Color(37, 52, 18));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreUsuario.setText("Jesus roberto garcia armenta");
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 18, 300, 27));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnDia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDia1ActionPerformed

    private void btnDia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDia2ActionPerformed

    private void btnDia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDia3ActionPerformed

    private void btnDia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDia4ActionPerformed

    private void btnDia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDia5ActionPerformed

    private void btnDia6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDia6ActionPerformed

    private void btnDia7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDia7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDia7ActionPerformed

    private void btnHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoyActionPerformed
        frame.mostrarInicio();
    }//GEN-LAST:event_btnHoyActionPerformed

    private void btnHabitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitosActionPerformed
        frame.mostrarListaHabitos();
    }//GEN-LAST:event_btnHabitosActionPerformed

    private void btnProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProgresoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        frame.agregarHabito(this);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensualActionPerformed
        frame.mostrarProgresoSemanal();
    }//GEN-LAST:event_btnMensualActionPerformed

    private void listarHabitos() throws FontFormatException, IOException, ControllerException {
        JPanel pnlHabitos = new JPanel();
        pnlHabitos.setLayout(new BoxLayout(pnlHabitos, BoxLayout.Y_AXIS));  // Usar BoxLayout para colocar los hábitos en forma vertical
        pnlHabitos.setOpaque(false);

        JScrollPane scpHabitos = new JScrollPane(pnlHabitos);
        scpHabitos.setOpaque(false);
        scpHabitos.getViewport().setOpaque(false);
        scpHabitos.setBorder(null);
        scpHabitos.getVerticalScrollBar().setUnitIncrement(16);
        scpHabitos.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scpHabitos.setPreferredSize(new Dimension(700, 390));  // Ajusta el tamaño del JScrollPane si es necesario
        // Agregar el JScrollPane al contenedor principal

        // Añadir hábitos
        Date[] limitesMes = gestionar.obtenerLimitesMes(new Date());

        List<ProgresoHabitoDTO> progresoHabitos = gestionar.obtenerProgresoHabitos(
                Sesion.getCuenta(),
                limitesMes[0],
                limitesMes[1]);

        // Añadir hábitos
        for (ProgresoHabitoDTO progresoHabito : progresoHabitos) {
            agregarHabito(progresoHabito.getNombreHabito(),
                    progresoHabito.getDiasRealizados(),
                    progresoHabito.getDiasTotales() * 4,
                    pnlHabitos);
        }
        pnlContenedorHabitos.add(scpHabitos);
    }

    private void agregarHabito(String nombreHabito, int diasRealizados, int diasTotales, JPanel parentPanel) throws FontFormatException, IOException {
        HabitPanel habit = new HabitPanel(nombreHabito, diasRealizados, diasTotales);

        parentPanel.add(habit);

        // Refrescar el panel
        parentPanel.revalidate();
        parentPanel.repaint();
    }

// Panel personalizado para cada hábito
    private class HabitPanel extends JPanel {

        public HabitPanel(String nombreHabito, int diasRealizados, int diasTotales) throws FontFormatException, IOException {
            setLayout(new GridBagLayout());
            GridBagConstraints gbc = new GridBagConstraints();
            setPreferredSize(new Dimension(0, 60));  // Altura ajustada
            setMaximumSize(new Dimension(Integer.MAX_VALUE, 60));  // Establece la altura máxima

            // Etiqueta con el nombre del hábito
            JLabel nameLabel = new JLabel(nombreHabito);
            nameLabel.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-Regular.ttf", 18F));
            setOpaque(false);

            // Configurar constraints para nameLabel
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.gridwidth = 2;  // Ocupa dos columnas
            gbc.anchor = GridBagConstraints.WEST;
            gbc.insets = new Insets(10, 0, 0, 0);  // Espacio inferior
            add(nameLabel, gbc);

            // Etiqueta para los días cumplidos
            JLabel diasLabel = new JLabel(diasRealizados + "/" + diasTotales);
            diasLabel.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-SemiBold.ttf", 18F));

            // Configurar constraints para diasLabel
            gbc.gridx = 0;
            gbc.gridy = 1;
            gbc.gridwidth = 1;  // Solo una columna
            gbc.anchor = GridBagConstraints.WEST;
            gbc.insets = new Insets(0, 0, 0, 0);  // Espacio inferior
            add(diasLabel, gbc);

            // Barra de progreso
            JProgressBar jpb = new JProgressBar(0, diasTotales);  // Rango de la barra
            jpb.setValue(diasRealizados);  // Valor actual (puedes cambiarlo dinámicamente)
            jpb.setPreferredSize(new Dimension(100, 10));
            jpb.setMinimumSize(new Dimension(100, 10));
            jpb.setForeground(new Color(118, 152, 82));
            jpb.setBackground(new Color(245, 245, 245));

            // Configurar constraints para jpb
            gbc.gridx = 1;
            gbc.gridy = 1;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            gbc.weightx = 1.0;  // Permite que la barra de progreso se expanda
            gbc.insets = new Insets(0, 10, 0, 0);  // Espacio inferior

            add(jpb, gbc);
        }
    }

    private void setFonts() throws FontFormatException, IOException {
        lblNombreUsuario.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-Medium.ttf", 20F));
        lblMes.setFont(frame.cargarFuente("/fonts/Kurale/Kurale-Regular.ttf", 20F));
        Font semiBoldFont = frame.cargarFuente("/fonts/Nunito/static/Nunito-SemiBold.ttf", 26F);
        Font nunitoRegular = frame.cargarFuente("/fonts/Nunito/static/Nunito-Regular.ttf", 18F);
        lblProgresoHabitos.setFont(semiBoldFont);
        btnDia1.setFont(nunitoRegular);
        btnDia2.setFont(nunitoRegular);
        btnDia3.setFont(nunitoRegular);
        btnDia4.setFont(nunitoRegular);
        btnDia5.setFont(nunitoRegular);
        btnDia6.setFont(nunitoRegular);
        btnDia7.setFont(nunitoRegular);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnDia1;
    private javax.swing.JButton btnDia2;
    private javax.swing.JButton btnDia3;
    private javax.swing.JButton btnDia4;
    private javax.swing.JButton btnDia5;
    private javax.swing.JButton btnDia6;
    private javax.swing.JButton btnDia7;
    private javax.swing.JButton btnHabitos;
    private javax.swing.JButton btnHoy;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JButton btnMensual;
    private javax.swing.JButton btnProgreso;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblMensual;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblProgresoHabitos;
    private javax.swing.JPanel pnlContenedorHabitos;
    // End of variables declaration//GEN-END:variables
}
