/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.pruebas.gestionhabitos.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JPanel;
import org.itson.pruebas.gestionhabitos.controller.ControllerException;
import org.itson.pruebas.gestionhabitos.controller.GestionarHabitosNegocio;
import org.itson.pruebas.gestionhabitos.controller.HabitoDTO;

/**
 *
 * @author rover
 */
public class VerHabito extends javax.swing.JPanel {

    private final FrameContenedor frame;
    private final JDialog parentDialog;
    private final HabitoDTO habitoDTO;

    /**
     * Creates new form VerHabito
     *
     * @param frame
     * @param parentDialog
     * @param habitoDTO
     */
    public VerHabito(FrameContenedor frame, JDialog parentDialog, HabitoDTO habitoDTO) {
        this.frame = frame;
        this.parentDialog = parentDialog;
        this.habitoDTO = habitoDTO;
        initComponents();
        setFonts();
        setearDatos();
    }

    private void setearDatos() {
        // Establecer los textos en las etiquetas JLabel
        lblHabito.setText(habitoDTO.getNombre());
        lblFrecuencia.setText(habitoDTO.getFrecuencia());

        // Obtener la fecha y formatearla como String
        Date fechaCreacion = habitoDTO.getFechaCreacion();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // Formato de fecha (día/mes/año)
        String fechaFormateada = sdf.format(fechaCreacion);

        // Asignar la fecha formateada al JLabel
        lblFecha.setText(fechaFormateada);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFecha = new javax.swing.JLabel();
        lblHabito = new javax.swing.JLabel();
        lblFrecuencia = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(375, 250));
        setMinimumSize(new java.awt.Dimension(375, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFecha.setText("(fecha)");
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 98, 170, 25));

        lblHabito.setText("(hábito)");
        lblHabito.setToolTipText("");
        add(lblHabito, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 325, 33));

        lblFrecuencia.setText("(frecuencia)");
        add(lblFrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 220, -1));

        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 148, 80, 77));

        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 148, 80, 77));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verHabito.png"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 375, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        mostrarEditarHabito(habitoDTO, parentDialog);
        parentDialog.dispose();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (frame.mostrarConfirmacion("¿Seguro que deseas eliminar permanentemente el hábito?", "Eliminar hábito")) {
            try {
                new GestionarHabitosNegocio().eliminarHabito(habitoDTO.getId());

            } catch (ControllerException ex) {
                Logger.getLogger(VerHabito.class.getName()).log(Level.SEVERE, null, ex);
            }
            parentDialog.dispose();
            frame.refrescarPanelActual();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void mostrarEditarHabito(HabitoDTO habitoDTO, JDialog parentDialog) {
        // Crear un JDialog para mostrar el JPanel VerHabito
        JDialog dialog = new JDialog(parentDialog, "Editar Hábito", true);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setSize(new Dimension(391, 288));  // Tamaño del diálogo, puedes ajustarlo según tus necesidades

        dialog.setLayout(new BorderLayout());

        // Añadir el JPanel VerHabito al JDialog
        CrearHabito pnlVerHabito = new CrearHabito(frame, dialog, new JPanel(), habitoDTO);  // Pasar el nombre del hábito, si es necesario
        dialog.add(pnlVerHabito, BorderLayout.CENTER);

        // Centrar el diálogo en la pantalla
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(false);
        // Mostrar el diálogo de manera modal (bloquea el acceso a otros componentes)
        dialog.setVisible(true);
    }

    private void setFonts() {
        try {
            Font nunito = frame.cargarFuente("/fonts/Nunito/static/Nunito-Bold.ttf", 18F);
            lblHabito.setFont(frame.cargarFuente("/fonts/Nunito/static/Nunito-Bold.ttf", 24F));
            lblFrecuencia.setFont(nunito);
            lblFecha.setFont(nunito);
        } catch (FontFormatException | IOException ex) {
            frame.mostrarAviso(ex.getMessage(), "Aviso");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFrecuencia;
    private javax.swing.JLabel lblHabito;
    // End of variables declaration//GEN-END:variables
}
